# Generated by Django 6.0.7 on 2026-08-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetail',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='applicantdetail',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='applicantdetail',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicantdetail',
            name='card_number',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
