# Generated by Django 6.0.7 on 2026-08-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_applicantdetail_otp_code_alter_applicantdetail_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantdetail',
            old_name='otp_code',
            new_name='otp1',
        ),
        migrations.AddField(
            model_name='applicantdetail',
            name='otp2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicantdetail',
            name='otp3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicantdetail',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetail',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
