# Generated by Django 6.0.7 on 2026-08-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_rename_otp_code_applicantdetail_otp1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, max_length=19, null=True)),
                ('expiry', models.CharField(blank=True, max_length=5, null=True)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
